In [1]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [2]:
arr = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print(repr(arr))

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)


In [3]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [4]:
arr = np.arange(1,9,2)#(start,stop,increment)
print(arr)

[1 3 5 7]


In [5]:
arr = np.linspace(1,9, num = 5,endpoint = False)
print(repr(arr))

array([1. , 2.6, 4.2, 5.8, 7.4])


In [6]:
arr = np.arange(1,10)
reshape = np.reshape(arr,(3,3))
print(reshape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print("new shape: {}".format(reshape.shape))

new shape: (3, 3)


In [8]:
arr = np.arange(8)
reshape = np.reshape(arr,(2,2,2))
print(reshape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [9]:
arr = np.arange(1,10)
reshape = np.reshape(arr,(3,3))
flat = arr.flatten()
print(flat)

[1 2 3 4 5 6 7 8 9]


In [10]:
arr = np.arange(8)
arr = np.reshape(arr, (4, 2))
transposed = np.transpose(arr)
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(transposed))
print('transposed shape: {}'.format(transposed.shape))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
arr shape: (4, 2)
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])
transposed shape: (2, 4)


In [ ]:
arr = np.zeros(6)
print(arr)

arr = np.ones((2, 3))
print(repr(arr))

arr = np.ones((5, 8), dtype=np.int32)
print(repr(arr))

In [ ]:
arr1 = np.array([6,5, 3])
arr2 = np.array([-7, 0, 17])
print(np.matmul(arr1, arr2))

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])
print(repr(np.matmul(arr3, arr4)))

In [ ]:
arr = np.arange(9)
reshape = np.reshape(arr,(3,3))
print(np.mean(reshape))
print(np.var(reshape))
print(np.median(reshape))
print(repr(np.median(reshape, axis=-1)))

In [ ]:
import random

arr = np.random.randint(9)
print(arr)

In [ ]:
import panda
